### ISSUE TITLE
Error building gpufetch (undefined references) on Ubuntu 21.10

### ISSUE THREAD

**Issue by mjohanning99** [Dr-Noob/gpufetch#9]
I was trying to build `gpufetch` on my machine, but keep on getting `undefined references` errors. I am running Ubuntu 21.10 and using an NVIDIA card. I am, unfortunately, not really an expert in this, but the output of running `./build.sh` can be found below. 

```
-- The CXX compiler identification is GNU 11.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The CUDA compiler identification is NVIDIA 11.5.119
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Could NOT find PCIUTILS (missing: PCIUTILS_LIBRARIES PCIUTILS_INCLUDE_DIR) 
-- pciutils not found, downloading and building a local copy...
-- ----------------------
-- gpufetch build report:
-- CUDA backend: ON
-- Intel backend: ON
-- ----------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mjo/gpufetch/build
-- Could NOT find PCIUTILS (missing: PCIUTILS_LIBRARIES PCIUTILS_INCLUDE_DIR) 
-- pciutils not found, downloading and building a local copy...
-- ----------------------
-- gpufetch build report:
-- CUDA backend: ON
-- Intel backend: ON
-- ----------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mjo/gpufetch/build
Scanning dependencies of target pciutils
[  3%] Creating directories for 'pciutils'
[  7%] Performing download step (git clone) for 'pciutils'
Cloning into 'pciutils'...
Already on 'master'
Your branch is up to date with 'origin/master'.
[ 11%] Performing update step for 'pciutils'
[ 14%] No patch step for 'pciutils'
[ 18%] No configure step for 'pciutils'
[ 22%] Performing build step for 'pciutils'
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
Configuring libpci for your system... x86_64--linux 5.13.0-23-generic x86_64 linux
Looking for access methods... sysfs proc i386-ports dump
Checking for zlib support... yes (auto-detected)
Checking for DNS support... yes (auto-detected)
Checking for libkmod... no (auto-detected)
Checking for udev hwdb support... yes (auto-detected)
Checking whether to build a shared library... no (set manually)
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
[ 25%] Performing install step for 'pciutils'
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
[ 29%] Completed 'pciutils'
[ 29%] Built target pciutils
Scanning dependencies of target cuda_backend
Scanning dependencies of target intel_backend
[ 40%] Building CXX object CMakeFiles/intel_backend.dir/src/intel/uarch.cpp.o
[ 40%] Building CXX object CMakeFiles/intel_backend.dir/src/intel/intel.cpp.o
[ 44%] Building CXX object CMakeFiles/intel_backend.dir/src/intel/pci.cpp.o
[ 44%] Building CXX object CMakeFiles/intel_backend.dir/src/intel/udev.cpp.o
[ 48%] Building CXX object CMakeFiles/intel_backend.dir/src/intel/cpuid.cpp.o
[ 51%] Building CXX object CMakeFiles/cuda_backend.dir/src/cuda/cuda.cpp.o
[ 55%] Building CXX object CMakeFiles/cuda_backend.dir/src/cuda/pci.cpp.o
[ 59%] Building CXX object CMakeFiles/cuda_backend.dir/src/cuda/uarch.cpp.o
[ 62%] Linking CXX static library libintel_backend.a
[ 62%] Built target intel_backend
[ 66%] Linking CXX static library libcuda_backend.a
[ 66%] Built target cuda_backend
Scanning dependencies of target gpufetch
[ 77%] Building CXX object CMakeFiles/gpufetch.dir/src/common/gpu.cpp.o
[ 77%] Building CXX object CMakeFiles/gpufetch.dir/src/common/pci.cpp.o
[ 77%] Building CXX object CMakeFiles/gpufetch.dir/src/common/printer.cpp.o
[ 81%] Building CXX object CMakeFiles/gpufetch.dir/src/common/args.cpp.o
[ 85%] Building CXX object CMakeFiles/gpufetch.dir/src/common/global.cpp.o
[ 88%] Building CXX object CMakeFiles/gpufetch.dir/src/common/uarch.cpp.o
[ 92%] Building CXX object CMakeFiles/gpufetch.dir/src/common/main.cpp.o
[ 96%] Building CXX object CMakeFiles/gpufetch.dir/src/common/master.cpp.o
[100%] Linking CXX executable gpufetch
/usr/bin/ld: /home/mjo/gpufetch/build/pciutils-install/lib/libpci.a(names-hwdb.o): in function `pci_id_hwdb_lookup':
names-hwdb.c:(.text+0xe4): undefined reference to `udev_hwdb_get_properties_list_entry'
/usr/bin/ld: names-hwdb.c:(.text+0xfc): undefined reference to `udev_list_entry_get_next'
/usr/bin/ld: names-hwdb.c:(.text+0x110): undefined reference to `udev_list_entry_get_name'
/usr/bin/ld: names-hwdb.c:(.text+0x12c): undefined reference to `udev_list_entry_get_value'
/usr/bin/ld: names-hwdb.c:(.text+0x19f): undefined reference to `udev_new'
/usr/bin/ld: names-hwdb.c:(.text+0x1ac): undefined reference to `udev_hwdb_new'
/usr/bin/ld: /home/mjo/gpufetch/build/pciutils-install/lib/libpci.a(names-hwdb.o): in function `pci_id_hwdb_free':
names-hwdb.c:(.text+0x2d2): undefined reference to `udev_hwdb_unref'
/usr/bin/ld: names-hwdb.c:(.text+0x2e8): undefined reference to `udev_unref'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/gpufetch.dir/build.make:210: gpufetch] Error 1
make[1]: *** [CMakeFiles/Makefile2:156: CMakeFiles/gpufetch.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

**Comment by Dr-Noob** [comment]
Thanks a lot for the report.

So, it seems that the CMake has an error, but I do not understand why it fails for you, but not for the rest of the compilations I have seen so far. 

Anyway, it should work with the latest patch I just submited. To try it, just update the project, checkout to the bugfix branch (`git checkout bugfix`) and compile it again with `./build.sh`.

**Comment by mjohanning99** [comment]
Thank you for your response, @Dr-Noob! I tried running `build.sh` again after checking out your `bugfix` branch and it worked immediately! 
<img width="970" alt="Screenshot 2022-01-11 at 21 02 08" src="https://user-images.githubusercontent.com/3389797/149013045-ca02d2a7-fc5e-42ce-a552-50ccd8e894de.png">

**Comment by Dr-Noob** [comment]
Okay, so I tried compiling with this patch in different machines and I found issues. 

So I just pushed a new commit in the `master` branch which works for me as before and, theoretically, should work for you too. Can you give it a try to confirm that it also works for you?

**Comment by mjohanning99** [comment]
I have just tried building gpufetch with your `master` branch and it still appears to work without any issues.

**Comment by Dr-Noob** [comment]
Great! That makes sense. Thanks for the help, closing the issue.
